openapi: '3.0.0'

info:
  version: '1.0.0'
  title: questBoardWebAPI

servers:
  - url: https://hogehoge/api/v1
    description: 開発環境

tags:
  - name: Quest
    description: クエスト関連API
  - name: User
    description: ユーザー関連API
  - name: Application
    description: クエスト参加申請・承認関連API
  
paths:
  '/quests':
    get:
      tags:
        - Quest
      summary: クエストの取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  quests:
                    type: array
                    items:
                      $ref: '#/components/schemas/Quest'

  '/create':
    post:
      tags:
        - Quest
      summary: クエストの立ち上げ
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                producer:
                  $ref: '#/components/schemas/User'
                questName:
                  type: string
                capacity:
                  type: integer
                  format: int64
                member_description:
                  type: string
                quest_description:
                  type: string
                period:
                  type: string
                  format: date
                schedule:
                  type: string
                tag:
                  $ref: '#/components/schemas/Tag'
                reward:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quest'

  '/update/{questId}':
    put:
      tags:
        - Quest
      summary: クエストの情報更新
      parameters: 
      - name: questId
        in: path
        schema:
          type: string
        description: クエストID
        required: true
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                producer:
                  $ref: '#/components/schemas/User'
                questName:
                  type: string
                capacity:
                  type: integer
                  format: int64
                member_description:
                  type: string
                quest_description:
                  type: string
                period:
                  type: string
                  format: date
                schedule:
                  type: string
                tag:
                  $ref: '#/components/schemas/Tag'
                reward:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quest'
  
  '/finish/{questId}':
    put:
      tags:
        - Quest
      summary: クエストの募集終了
      parameters: 
      - name: questId
        in: path
        schema:
          type: string
        description: クエストID
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quest'

  '/apply':
    post:
      tags:
        - Application
      summary: クエスト参加の申し込み
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quest:
                  $ref: '#/components/schemas/Quest'
                applicant:
                  $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
    
  '/cancel/{applicationId}':
    delete:
        tags:
          - Application
        summary: クエスト参加の辞退
        parameters: 
        - name: applicationId
          in: path
          schema:
            type: string
          description: 申請ID
          required: true
        responses:
          '200':
            description: OK

  '/approve/{applicationId}':
    put:
      tags:
        - Application
      summary: クエスト参加の承認
      parameters: 
      - name: applicationId
        in: path
        schema:
          type: string
        description: 申請ID
        required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                result:
                  type: boolean
                comment:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
components:
  schemas:
    User:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    Quest:
      properties:
        id: 
          type: integer
          format: int64
        producer:
          $ref: '#/components/schemas/User'
        member:
          type: array
          items:
            $ref: '#/components/schemas/User'
        questName:
          type: string
        capacity:
          type: integer
          format: int64
        memberDescription:
          type: string
        questDescription:
          type: string
        period:
          type: string
          format: date
        schedule:
          type: string
        tag:
          $ref: '#/components/schemas/Tag'
        reward:
          type: string
        isFinished:
          type: boolean
        craetedDate:
          type: string
          format: date-time
        updatedDate:
          type: string
          format: date-time
        finishedDate:
          type: string
          format: date-time

    Tag:
      properties:
        id: 
          type: integer
          format: int64
        name:
          type: string

    Application:
      properties:
        id: 
          type: integer
          format: int64
        quest:
          $ref: '#/components/schemas/Quest'
        applicant:
          $ref: '#/components/schemas/User'
        status: 
          type: boolean