openapi: '3.0.0'

info:
  version: '1.0.0'
  title: questBoardWebAPI

servers:
  - url: https://hogehoge/api/v1
    description: 開発環境

tags:
  - name: Quest
    description: クエスト関連API
  - name: User
    description: ユーザー関連API

paths:
  '/create':
    post:
      tags:
        - Quest
      summary: クエストの立ち上げ
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                producer:
                  $ref: '#/components/schemas/User'
                questName:
                  type: string
                capacity:
                  type: integer
                  format: int64
                member_description:
                  type: string
                quest_description:
                  type: string
                period:
                  type: string
                  format: date
                schedule:
                  type: string
                tag:
                  $ref: '#/components/schemas/Tag'
                reward:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quest'
components:
  schemas:
    User:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    Quest:
      properties:
        id: 
          type: integer
          format: int64
        producer:
          $ref: '#/components/schemas/User'
        questName:
          type: string
        capacity:
          type: integer
          format: int64
        member_description:
          type: string
        quest_description:
          type: string
        period:
          type: string
          format: date
        schedule:
          type: string
        tag:
          $ref: '#/components/schemas/Tag'
        reward:
          type: string
        craetedDate:
          type: string
          format: date-time
        updatedDate:
          type: string
          format: date-time
        deletedDate:
          type: string
          format: date-time

    Tag:
      properties:
        id: 
          type: integer
          format: int64
        name:
          type: string